### ISSUE TITLE
fix metadata 

### ISSUE THREAD

**Issue by krrishdholakia** [sdan/vlite#15]
metadata id is being stored as `metadata[idx]["index"]` but being returned as `metadata[id]` this is naturally causing KeyErrors 

<img width="563" alt="Screenshot 2023-07-14 at 3 58 53 PM" src="https://github.com/sdan/vlite/assets/17561003/1806c150-ae44-4ad1-9276-384b58e15bfb">

**Comment by Codie-Petersen** [comment]
And come to think of it, even if you do remember it, it is returning the metadata, not the text.

**Comment by Codie-Petersen** [comment]
@krrishdholakia I'm going to create a fork that incoporates a fix. The creator looks like they might be quite busy but I like this package too much not to use it.
