### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by krrishdholakia** [sdan/vlite#4]
hey! i tried to run this and it isn't working - tried in Colab
<img width="1183" alt="Screenshot 2023-07-05 at 1 32 51 PM" src="https://github.com/sdan/vlite/assets/17561003/92b6f34c-b8c1-41ec-8513-226a57f367fc">

**Comment by krrishdholakia** [comment]
cc: @sdan

**Comment by chumpblocckami** [comment]
Try switch 'mps' to 'cuda' if you have a GPU installed, or instead use 'cpu'. 
MPS is the device used by Mac systems,

**Comment by sdan** [comment]
thanks i just fixed this in 0.1.7
