### ISSUE TITLE
Embeddings are persisting between runs

### ISSUE THREAD

**Issue by HowieG** [sdan/vlite#5]
Every time a vlist instance is created the embeddings from previous instances persist. If I embed 100 chunks in one instance and then 200 in a second instance, the second instance will have 100+200=300 embeddings.

**Comment by manuel-soria** [comment]
Same happened to me, you can try changing `collection` parameter:

db = VLite(collection='different_name.npz')

I know it's not a fix, just a turnaround, we can probably work around a fix and create a PR for it

**Comment by HowieG** [comment]
I submitted a PR, @sdan knows just waiting on him to review
